# Generated by Django 3.2.5 on 2021-07-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210706_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
